# Generated by Django 5.1.1 on 2024-09-03 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'メニュー', 'verbose_name_plural': 'メニュー'},
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_bot.menu')),
            ],
            options={
                'verbose_name': 'お会計',
                'verbose_name_plural': 'お会計',
            },
        ),
    ]
