# Generated by Django 5.1.1 on 2024-09-03 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_bot', '0003_alter_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='genre_images/')),
            ],
            options={
                'verbose_name': 'ジャンル',
                'verbose_name_plural': 'ジャンル',
            },
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': '注文履歴', 'verbose_name_plural': '注文履歴'},
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_bot.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_bot.menugenre'),
        ),
    ]
